--1
BEGIN ISOLATION LEVEL READ COMMITTED;
SHOW TRANSACTION ISOLATION LEVEL;
SELECT * FROM pizzeria WHERE name  = 'Pizza Hut';

COMMIT;

--2
BEGIN ISOLATION LEVEL READ COMMITTED;
SHOW TRANSACTION ISOLATION LEVEL;
SELECT * FROM pizzeria WHERE name  = 'Pizza Hut';
UPDATE pizzeria SET rating = 3.6 WHERE name = 'Pizza Hut';
COMMIT;
