--1
BEGIN;
BEGIN ISOLATION LEVEL READ COMMITTED;
SHOW TRANSACTION ISOLATION LEVEL;
SELECT SUM(rating) FROM pizzeria;
COMMIT;

--2
BEGIN;
BEGIN ISOLATION LEVEL READ COMMITTED;
SHOW TRANSACTION ISOLATION LEVEL;
SELECT SUM(rating) FROM pizzeria;
UPDATE pizzeria SET rating = 1 WHERE name = 'Pizza Hut';
COMMIT;
