--1
BEGIN;
BEGIN ISOLATION LEVEL SERIALIZABLE;
SHOW TRANSACTION ISOLATION LEVEL;
SELECT * FROM pizzeria WHERE name  = 'Pizza Hut';

COMMIT;

--2
BEGIN;
BEGIN ISOLATION LEVEL SERIALIZABLE;
SHOW TRANSACTION ISOLATION LEVEL;
SELECT * FROM pizzeria WHERE name  = 'Pizza Hut';
UPDATE pizzeria SET rating = 3 WHERE name = 'Pizza Hut';
COMMIT;
